<?php

namespace AppBundle\Repository;

/**
 * EgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgressRepository extends \Doctrine\ORM\EntityRepository
{
}
