<?php

namespace AppBundle\Repository;

/**
 * IngressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngressRepository extends \Doctrine\ORM\EntityRepository
{
}
