<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cash extends \AppBundle\Entity\Cash implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'datetime', '' . "\0" . 'AppBundle\\Entity\\Cash' . "\0" . 'ingress', '' . "\0" . 'AppBundle\\Entity\\Cash' . "\0" . 'items', '' . "\0" . 'AppBundle\\Entity\\Cash' . "\0" . 'egress', '' . "\0" . 'AppBundle\\Entity\\Cash' . "\0" . 'provider', 'paymentType', 'comments', 'ammount'];
        }

        return ['__isInitialized__', 'id', 'datetime', '' . "\0" . 'AppBundle\\Entity\\Cash' . "\0" . 'ingress', '' . "\0" . 'AppBundle\\Entity\\Cash' . "\0" . 'items', '' . "\0" . 'AppBundle\\Entity\\Cash' . "\0" . 'egress', '' . "\0" . 'AppBundle\\Entity\\Cash' . "\0" . 'provider', 'paymentType', 'comments', 'ammount'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cash $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatetime($datetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatetime', [$datetime]);

        return parent::setDatetime($datetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatetime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatetime', []);

        return parent::getDatetime();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromised($promised)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromised', [$promised]);

        return parent::setPromised($promised);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromised()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromised', []);

        return parent::getPromised();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(\AppBundle\Entity\User $client = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setIngress(\AppBundle\Entity\Ingress $ingress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIngress', [$ingress]);

        return parent::setIngress($ingress);
    }

    /**
     * {@inheritDoc}
     */
    public function getIngress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIngress', []);

        return parent::getIngress();
    }

    /**
     * {@inheritDoc}
     */
    public function setEgress(\AppBundle\Entity\Egress $egress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEgress', [$egress]);

        return parent::setEgress($egress);
    }

    /**
     * {@inheritDoc}
     */
    public function getEgress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEgress', []);

        return parent::getEgress();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvider(\AppBundle\Entity\Provider $provider = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvider', [$provider]);

        return parent::setProvider($provider);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvider', []);

        return parent::getProvider();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentType($paymentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentType', [$paymentType]);

        return parent::setPaymentType($paymentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentType', []);

        return parent::getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments($comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', [$comments]);

        return parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getcomments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcomments', []);

        return parent::getcomments();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmmount($ammount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmmount', [$ammount]);

        return parent::setAmmount($ammount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmmount', []);

        return parent::getAmmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItems', []);

        return parent::getItems();
    }

}
